//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("Authentication", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class AuthenticationDetail {
    
    private string userNameField;
    
    private string passwordField;
    
    private string newPasswordField;
    
    private string twoFactorPasswordField;
    
    /// <remarks/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public string NewPassword {
        get {
            return this.newPasswordField;
        }
        set {
            this.newPasswordField = value;
        }
    }
    
    /// <remarks/>
    public string TwoFactorPassword {
        get {
            return this.twoFactorPasswordField;
        }
        set {
            this.twoFactorPasswordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class FileContent {
    
    private EncodingTypes encodingField;
    
    private string fileBufferField;
    
    private string _SequenceField;
    
    /// <remarks/>
    public EncodingTypes Encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    public string FileBuffer {
        get {
            return this.fileBufferField;
        }
        set {
            this.fileBufferField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _Sequence {
        get {
            return this._SequenceField;
        }
        set {
            this._SequenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public enum EncodingTypes {
    
    /// <remarks/>
    Base64,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class FileContentDetail {
    
    private FileContentInfo fileContentInfoField;
    
    private FileContent[] fileContentField;
    
    /// <remarks/>
    public FileContentInfo FileContentInfo {
        get {
            return this.fileContentInfoField;
        }
        set {
            this.fileContentInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileContent")]
    public FileContent[] FileContent {
        get {
            return this.fileContentField;
        }
        set {
            this.fileContentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class FileContentInfo {
    
    private string pageCountField;
    
    private EmbededFileTypes embeddedFileTypeField;
    
    private ActionCode actionCodeField;
    
    private string _IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string PageCount {
        get {
            return this.pageCountField;
        }
        set {
            this.pageCountField = value;
        }
    }
    
    /// <remarks/>
    public EmbededFileTypes EmbeddedFileType {
        get {
            return this.embeddedFileTypeField;
        }
        set {
            this.embeddedFileTypeField = value;
        }
    }
    
    /// <remarks/>
    public ActionCode ActionCode {
        get {
            return this.actionCodeField;
        }
        set {
            this.actionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public enum EmbededFileTypes {
    
    /// <remarks/>
    Single_Page_Tiff,
    
    /// <remarks/>
    Multi_Page_Tiff,
    
    /// <remarks/>
    PRIA_XML,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public enum ActionCode {
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    New,
    
    /// <remarks/>
    Edit,
    
    /// <remarks/>
    Delete,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class FileContentDetails {
    
    private FileContentDetail recordableFileContentDetailField;
    
    private FileContentDetail pCORFileContentDetailField;
    
    private FileContentDetail otherFileContentDetailField;
    
    /// <remarks/>
    public FileContentDetail RecordableFileContentDetail {
        get {
            return this.recordableFileContentDetailField;
        }
        set {
            this.recordableFileContentDetailField = value;
        }
    }
    
    /// <remarks/>
    public FileContentDetail PCORFileContentDetail {
        get {
            return this.pCORFileContentDetailField;
        }
        set {
            this.pCORFileContentDetailField = value;
        }
    }
    
    /// <remarks/>
    public FileContentDetail OtherFileContentDetail {
        get {
            return this.otherFileContentDetailField;
        }
        set {
            this.otherFileContentDetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class NameDetail {
    
    private NameTypes typeField;
    
    private string valueField;
    
    private string prefixField;
    
    private string firstNameField;
    
    private string middleNameField;
    
    private string lastNameField;
    
    private string suffixField;
    
    private ActionCode actionCodeField;
    
    private System.DateTime createTimeStampField;
    
    private bool createTimeStampFieldSpecified;
    
    private System.DateTime editTimeStampField;
    
    private string _IDField;
    
    /// <remarks/>
    public NameTypes Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public string Prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string Suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    public ActionCode ActionCode {
        get {
            return this.actionCodeField;
        }
        set {
            this.actionCodeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTimeStamp {
        get {
            return this.createTimeStampField;
        }
        set {
            this.createTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateTimeStampSpecified {
        get {
            return this.createTimeStampFieldSpecified;
        }
        set {
            this.createTimeStampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EditTimeStamp {
        get {
            return this.editTimeStampField;
        }
        set {
            this.editTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public enum NameTypes {
    
    /// <remarks/>
    Grantor,
    
    /// <remarks/>
    Grantee,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class FeeDetail {
    
    private string codeField;
    
    private string descriptionField;
    
    private decimal amountField;
    
    private ActionCode actionCodeField;
    
    private System.DateTime createTimeStampField;
    
    private bool createTimeStampFieldSpecified;
    
    private System.DateTime editTimeStampField;
    
    private string _IDField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public ActionCode ActionCode {
        get {
            return this.actionCodeField;
        }
        set {
            this.actionCodeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTimeStamp {
        get {
            return this.createTimeStampField;
        }
        set {
            this.createTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateTimeStampSpecified {
        get {
            return this.createTimeStampFieldSpecified;
        }
        set {
            this.createTimeStampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EditTimeStamp {
        get {
            return this.editTimeStampField;
        }
        set {
            this.editTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class CityDetail {
    
    private string codeField;
    
    private string descriptionField;
    
    private ActionCode actionCodeField;
    
    private System.DateTime createTimeStampField;
    
    private bool createTimeStampFieldSpecified;
    
    private System.DateTime editTimeStampField;
    
    private string _IDField;
    
    private string _CountyIDField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public ActionCode ActionCode {
        get {
            return this.actionCodeField;
        }
        set {
            this.actionCodeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTimeStamp {
        get {
            return this.createTimeStampField;
        }
        set {
            this.createTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateTimeStampSpecified {
        get {
            return this.createTimeStampFieldSpecified;
        }
        set {
            this.createTimeStampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EditTimeStamp {
        get {
            return this.editTimeStampField;
        }
        set {
            this.editTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _CountyID {
        get {
            return this._CountyIDField;
        }
        set {
            this._CountyIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class TitleDetail {
    
    private string codeField;
    
    private string descriptionField;
    
    private int sequenceField;
    
    private bool sequenceFieldSpecified;
    
    private ActionCode actionCodeField;
    
    private System.DateTime createTimeStampField;
    
    private bool createTimeStampFieldSpecified;
    
    private System.DateTime editTimeStampField;
    
    private string _IDField;
    
    private string _CountyIDField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public int Sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SequenceSpecified {
        get {
            return this.sequenceFieldSpecified;
        }
        set {
            this.sequenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ActionCode ActionCode {
        get {
            return this.actionCodeField;
        }
        set {
            this.actionCodeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTimeStamp {
        get {
            return this.createTimeStampField;
        }
        set {
            this.createTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateTimeStampSpecified {
        get {
            return this.createTimeStampFieldSpecified;
        }
        set {
            this.createTimeStampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EditTimeStamp {
        get {
            return this.editTimeStampField;
        }
        set {
            this.editTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _CountyID {
        get {
            return this._CountyIDField;
        }
        set {
            this._CountyIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class DocumentInfo {
    
    private long numberField;
    
    private bool numberFieldSpecified;
    
    private System.DateTime recordedTimeStampField;
    
    private bool recordedTimeStampFieldSpecified;
    
    private FileContentInfo recordableFileContentInfoField;
    
    private FileContentInfo pCORFileContentInfoField;
    
    private FileContentInfo otherFileContentInfoField;
    
    private DocumentMediaStatusCode statusCodeField;
    
    private ActionCode actionCodeField;
    
    private int sequenceField;
    
    private string assessorParcelNumberField;
    
    private decimal transferTaxAmountField;
    
    private bool transferTaxAmountFieldSpecified;
    
    private decimal saleAmountField;
    
    private bool saleAmountFieldSpecified;
    
    private TitleDetail[] titlesField;
    
    private CityDetail[] citiesField;
    
    private FeeDetail[] feesField;
    
    private NameDetail[] namesField;
    
    private int versionField;
    
    private System.DateTime createTimeStampField;
    
    private bool createTimeStampFieldSpecified;
    
    private System.DateTime editTimeStampField;
    
    private MemoDetail[] memosField;
    
    private string _IDField;
    
    private string _ExternalIDField;
    
    /// <remarks/>
    public long Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumberSpecified {
        get {
            return this.numberFieldSpecified;
        }
        set {
            this.numberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime RecordedTimeStamp {
        get {
            return this.recordedTimeStampField;
        }
        set {
            this.recordedTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecordedTimeStampSpecified {
        get {
            return this.recordedTimeStampFieldSpecified;
        }
        set {
            this.recordedTimeStampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public FileContentInfo RecordableFileContentInfo {
        get {
            return this.recordableFileContentInfoField;
        }
        set {
            this.recordableFileContentInfoField = value;
        }
    }
    
    /// <remarks/>
    public FileContentInfo PCORFileContentInfo {
        get {
            return this.pCORFileContentInfoField;
        }
        set {
            this.pCORFileContentInfoField = value;
        }
    }
    
    /// <remarks/>
    public FileContentInfo OtherFileContentInfo {
        get {
            return this.otherFileContentInfoField;
        }
        set {
            this.otherFileContentInfoField = value;
        }
    }
    
    /// <remarks/>
    public DocumentMediaStatusCode StatusCode {
        get {
            return this.statusCodeField;
        }
        set {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    public ActionCode ActionCode {
        get {
            return this.actionCodeField;
        }
        set {
            this.actionCodeField = value;
        }
    }
    
    /// <remarks/>
    public int Sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
    
    /// <remarks/>
    public string AssessorParcelNumber {
        get {
            return this.assessorParcelNumberField;
        }
        set {
            this.assessorParcelNumberField = value;
        }
    }
    
    /// <remarks/>
    public decimal TransferTaxAmount {
        get {
            return this.transferTaxAmountField;
        }
        set {
            this.transferTaxAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransferTaxAmountSpecified {
        get {
            return this.transferTaxAmountFieldSpecified;
        }
        set {
            this.transferTaxAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal SaleAmount {
        get {
            return this.saleAmountField;
        }
        set {
            this.saleAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SaleAmountSpecified {
        get {
            return this.saleAmountFieldSpecified;
        }
        set {
            this.saleAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Title", IsNullable=false)]
    public TitleDetail[] Titles {
        get {
            return this.titlesField;
        }
        set {
            this.titlesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("City", IsNullable=false)]
    public CityDetail[] Cities {
        get {
            return this.citiesField;
        }
        set {
            this.citiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Fee", IsNullable=false)]
    public FeeDetail[] Fees {
        get {
            return this.feesField;
        }
        set {
            this.feesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Name", IsNullable=false)]
    public NameDetail[] Names {
        get {
            return this.namesField;
        }
        set {
            this.namesField = value;
        }
    }
    
    /// <remarks/>
    public int Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTimeStamp {
        get {
            return this.createTimeStampField;
        }
        set {
            this.createTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateTimeStampSpecified {
        get {
            return this.createTimeStampFieldSpecified;
        }
        set {
            this.createTimeStampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EditTimeStamp {
        get {
            return this.editTimeStampField;
        }
        set {
            this.editTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DocumentMemos", IsNullable=false)]
    public MemoDetail[] Memos {
        get {
            return this.memosField;
        }
        set {
            this.memosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string _ExternalID {
        get {
            return this._ExternalIDField;
        }
        set {
            this._ExternalIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public enum DocumentMediaStatusCode {
    
    /// <remarks/>
    New,
    
    /// <remarks/>
    Uploaded,
    
    /// <remarks/>
    Correction,
    
    /// <remarks/>
    Corrected,
    
    /// <remarks/>
    Rejected,
    
    /// <remarks/>
    Recorded,
    
    /// <remarks/>
    Purged,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class MemoDetail {
    
    private string memoField;
    
    private string userDisplayNameField;
    
    private string userNameField;
    
    private MemoTypes typeField;
    
    private bool typeFieldSpecified;
    
    private ActionCode actionCodeField;
    
    private System.DateTime createTimeStampField;
    
    private bool createTimeStampFieldSpecified;
    
    private System.DateTime editTimeStampField;
    
    private string _IDField;
    
    /// <remarks/>
    public string Memo {
        get {
            return this.memoField;
        }
        set {
            this.memoField = value;
        }
    }
    
    /// <remarks/>
    public string UserDisplayName {
        get {
            return this.userDisplayNameField;
        }
        set {
            this.userDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public MemoTypes Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ActionCode ActionCode {
        get {
            return this.actionCodeField;
        }
        set {
            this.actionCodeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTimeStamp {
        get {
            return this.createTimeStampField;
        }
        set {
            this.createTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateTimeStampSpecified {
        get {
            return this.createTimeStampFieldSpecified;
        }
        set {
            this.createTimeStampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EditTimeStamp {
        get {
            return this.editTimeStampField;
        }
        set {
            this.editTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public enum MemoTypes {
    
    /// <remarks/>
    Note,
    
    /// <remarks/>
    Reject_Reason,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class RequestingPartyInfo {
    
    private string nameField;
    
    private bool isChargingPartyField;
    
    private bool isChargingPartyFieldSpecified;
    
    private string _IDField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool IsChargingParty {
        get {
            return this.isChargingPartyField;
        }
        set {
            this.isChargingPartyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsChargingPartySpecified {
        get {
            return this.isChargingPartyFieldSpecified;
        }
        set {
            this.isChargingPartyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class SubmittingPartyInfo {
    
    private string nameField;
    
    private PartyTypes partyTypeField;
    
    private bool partyTypeFieldSpecified;
    
    private string _IDField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public PartyTypes PartyType {
        get {
            return this.partyTypeField;
        }
        set {
            this.partyTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PartyTypeSpecified {
        get {
            return this.partyTypeFieldSpecified;
        }
        set {
            this.partyTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public enum PartyTypes {
    
    /// <remarks/>
    Agent,
    
    /// <remarks/>
    Authorized_Submitter,
    
    /// <remarks/>
    Government_Agency,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class UserInfo {
    
    private string userNameField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    /// <remarks/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public partial class ProcessQueueDetail {
    
    private string nameField;
    
    private string descriptionField;
    
    private System.DateTime openTimeField;
    
    private bool openTimeFieldSpecified;
    
    private System.DateTime closeTimeField;
    
    private bool closeTimeFieldSpecified;
    
    private string _IDField;
    
    private string _CountyIDField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime OpenTime {
        get {
            return this.openTimeField;
        }
        set {
            this.openTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OpenTimeSpecified {
        get {
            return this.openTimeFieldSpecified;
        }
        set {
            this.openTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime CloseTime {
        get {
            return this.closeTimeField;
        }
        set {
            this.closeTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CloseTimeSpecified {
        get {
            return this.closeTimeFieldSpecified;
        }
        set {
            this.closeTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _CountyID {
        get {
            return this._CountyIDField;
        }
        set {
            this._CountyIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("Session", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class SessionDetail {
    
    private string sessionTokenIDField;
    
    private bool passwordExpiredField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string userTypeField;
    
    /// <remarks/>
    public string SessionTokenID {
        get {
            return this.sessionTokenIDField;
        }
        set {
            this.sessionTokenIDField = value;
        }
    }
    
    /// <remarks/>
    public bool PasswordExpired {
        get {
            return this.passwordExpiredField;
        }
        set {
            this.passwordExpiredField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string UserType {
        get {
            return this.userTypeField;
        }
        set {
            this.userTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("BatchWithDocuments", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class BatchWithDocumentsDetail {
    
    private BatchDetail batchField;
    
    private DocumentDetail[] documentsField;
    
    /// <remarks/>
    public BatchDetail Batch {
        get {
            return this.batchField;
        }
        set {
            this.batchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable=false)]
    public DocumentDetail[] Documents {
        get {
            return this.documentsField;
        }
        set {
            this.documentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("Batch", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class BatchDetail {
    
    private string nameField;
    
    private CountyInfo countyField;
    
    private ProcessQueueDetail processQueueField;
    
    private string transactionNumberField;
    
    private BatchMediaStatusCode statusCodeField;
    
    private UserInfo checkedOutByField;
    
    private System.DateTime checkedOutTimeStampField;
    
    private bool checkedOutTimeStampFieldSpecified;
    
    private SubmittingPartyInfo submittingPartyField;
    
    private RequestingPartyInfo requestingPartyField;
    
    private bool isConcurrentField;
    
    private System.DateTime createTimeStampField;
    
    private bool createTimeStampFieldSpecified;
    
    private System.DateTime editTimeStampField;
    
    private MemoDetail[] memosField;
    
    private DocumentInfo[] documentsField;
    
    private string _IDField;
    
    private string _SubmissionIDField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public CountyInfo County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }
    
    /// <remarks/>
    public ProcessQueueDetail ProcessQueue {
        get {
            return this.processQueueField;
        }
        set {
            this.processQueueField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionNumber {
        get {
            return this.transactionNumberField;
        }
        set {
            this.transactionNumberField = value;
        }
    }
    
    /// <remarks/>
    public BatchMediaStatusCode StatusCode {
        get {
            return this.statusCodeField;
        }
        set {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    public UserInfo CheckedOutBy {
        get {
            return this.checkedOutByField;
        }
        set {
            this.checkedOutByField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CheckedOutTimeStamp {
        get {
            return this.checkedOutTimeStampField;
        }
        set {
            this.checkedOutTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CheckedOutTimeStampSpecified {
        get {
            return this.checkedOutTimeStampFieldSpecified;
        }
        set {
            this.checkedOutTimeStampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public SubmittingPartyInfo SubmittingParty {
        get {
            return this.submittingPartyField;
        }
        set {
            this.submittingPartyField = value;
        }
    }
    
    /// <remarks/>
    public RequestingPartyInfo RequestingParty {
        get {
            return this.requestingPartyField;
        }
        set {
            this.requestingPartyField = value;
        }
    }
    
    /// <remarks/>
    public bool IsConcurrent {
        get {
            return this.isConcurrentField;
        }
        set {
            this.isConcurrentField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTimeStamp {
        get {
            return this.createTimeStampField;
        }
        set {
            this.createTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateTimeStampSpecified {
        get {
            return this.createTimeStampFieldSpecified;
        }
        set {
            this.createTimeStampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EditTimeStamp {
        get {
            return this.editTimeStampField;
        }
        set {
            this.editTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("BatchMemos", IsNullable=false)]
    public MemoDetail[] Memos {
        get {
            return this.memosField;
        }
        set {
            this.memosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable=false)]
    public DocumentInfo[] Documents {
        get {
            return this.documentsField;
        }
        set {
            this.documentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string _SubmissionID {
        get {
            return this._SubmissionIDField;
        }
        set {
            this._SubmissionIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("County", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class CountyInfo {
    
    private string nameField;
    
    private string fipsStateCodeField;
    
    private string fipsCountyCodeField;
    
    private string logoField;
    
    private string _IDField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string FipsStateCode {
        get {
            return this.fipsStateCodeField;
        }
        set {
            this.fipsStateCodeField = value;
        }
    }
    
    /// <remarks/>
    public string FipsCountyCode {
        get {
            return this.fipsCountyCodeField;
        }
        set {
            this.fipsCountyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Logo {
        get {
            return this.logoField;
        }
        set {
            this.logoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
public enum BatchMediaStatusCode {
    
    /// <remarks/>
    New,
    
    /// <remarks/>
    Submitter_Uploading,
    
    /// <remarks/>
    Uploaded_By_Submitter,
    
    /// <remarks/>
    Downloaded_By_County,
    
    /// <remarks/>
    County_Uploading_Correction,
    
    /// <remarks/>
    Correction_Uploaded_By_County,
    
    /// <remarks/>
    Correction_Downloaded_By_Submitter,
    
    /// <remarks/>
    Submitter_Uploading_Corrected,
    
    /// <remarks/>
    Corrected_Uploaded_By_Submitter,
    
    /// <remarks/>
    Corrected_Downloaded_By_County,
    
    /// <remarks/>
    County_Uploading_Completed,
    
    /// <remarks/>
    Completed_Uploaded_By_County,
    
    /// <remarks/>
    Completed_Downloaded_By_Submitter,
    
    /// <remarks/>
    Purged,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("Document", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class DocumentDetail {
    
    private DocumentMediaStatusCode statusCodeField;
    
    private FileContentDetails fileContentDetailsField;
    
    private string _IDField;
    
    private string _BatchIDField;
    
    private string _ExternalIDField;
    
    /// <remarks/>
    public DocumentMediaStatusCode StatusCode {
        get {
            return this.statusCodeField;
        }
        set {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    public FileContentDetails FileContentDetails {
        get {
            return this.fileContentDetailsField;
        }
        set {
            this.fileContentDetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _ID {
        get {
            return this._IDField;
        }
        set {
            this._IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _BatchID {
        get {
            return this._BatchIDField;
        }
        set {
            this._BatchIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string _ExternalID {
        get {
            return this._ExternalIDField;
        }
        set {
            this._ExternalIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("Batches", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class BatchesDetail {
    
    private BatchDetail[] batchField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Batch")]
    public BatchDetail[] Batch {
        get {
            return this.batchField;
        }
        set {
            this.batchField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("Titles", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class TitlesDetail {
    
    private TitleDetail[] titleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Title")]
    public TitleDetail[] Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("Cities", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class CitiesDetail {
    
    private CityDetail[] cityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("City")]
    public CityDetail[] City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("ProcessQueues", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class ProcessQueuesDetail {
    
    private ProcessQueueDetail[] processQueueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProcessQueue")]
    public ProcessQueueDetail[] ProcessQueue {
        get {
            return this.processQueueField;
        }
        set {
            this.processQueueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("Counties", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class CountiesInfo {
    
    private CountyInfo[] countyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("County")]
    public CountyInfo[] County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("RequestingParties", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class RequestingPartiesInfo {
    
    private RequestingPartyInfo[] requestingPartyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RequestingParty")]
    public RequestingPartyInfo[] RequestingParty {
        get {
            return this.requestingPartyField;
        }
        set {
            this.requestingPartyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("SubmittingParties", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class SubmittingPartiesInfo {
    
    private SubmittingPartyInfo[] submittingPartyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubmittingParty")]
    public SubmittingPartyInfo[] SubmittingParty {
        get {
            return this.submittingPartyField;
        }
        set {
            this.submittingPartyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("IndexOptions", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class IndexOptionDetail {
    
    private bool enableTitleIndexField;

    private bool requireTitleIndexField;
    
    private bool enableNamesIndexField;

    private bool requireNamesIndexField;
    
    private bool enableAPNIndexField;

    private bool requireAPNIndexField;
    
    private bool enableTransferTaxIndexField;

    private bool requireTransferTaxIndexField;
    
    private bool enableAmountSaleIndexField;

    private bool requireAmountSaleIndexField;
    
    private bool enableCityIndexField;

    private bool requireCityIndexField;
    
    private bool enableConcurrentIndexField;

    private bool requireConcurrentIndexField;
    
    private bool enableRequestingPartyField;

    private bool requireRequestingPartyField;
    
    private string _CountyIDField;
    
    /// <remarks/>
    public bool EnableTitleIndex {
        get {
            return this.enableTitleIndexField;
        }
        set {
            this.enableTitleIndexField = value;
        }
    }

    /// <remarks/>
    public bool RequireTitleIndex
    {
        get
        {
            return this.requireTitleIndexField;
        }
        set
        {
            this.requireTitleIndexField = value;
        }
    }
    
    /// <remarks/>
    public bool EnableNamesIndex {
        get {
            return this.enableNamesIndexField;
        }
        set {
            this.enableNamesIndexField = value;
        }
    }

    /// <remarks/>
    public bool RequireNamesIndex
    {
        get
        {
            return this.requireNamesIndexField;
        }
        set
        {
            this.requireNamesIndexField = value;
        }
    }
    
    /// <remarks/>
    public bool EnableAPNIndex {
        get {
            return this.enableAPNIndexField;
        }
        set {
            this.enableAPNIndexField = value;
        }
    }

    /// <remarks/>
    public bool RequireAPNIndex
    {
        get
        {
            return this.requireAPNIndexField;
        }
        set
        {
            this.requireAPNIndexField = value;
        }
    }
    
    /// <remarks/>
    public bool EnableTransferTaxIndex {
        get {
            return this.enableTransferTaxIndexField;
        }
        set {
            this.enableTransferTaxIndexField = value;
        }
    }

    /// <remarks/>
    public bool RequireTransferTaxIndex
    {
        get
        {
            return this.requireTransferTaxIndexField;
        }
        set
        {
            this.requireTransferTaxIndexField = value;
        }
    }
    
    /// <remarks/>
    public bool EnableAmountSaleIndex {
        get {
            return this.enableAmountSaleIndexField;
        }
        set {
            this.enableAmountSaleIndexField = value;
        }
    }

    /// <remarks/>
    public bool RequireAmountSaleIndex
    {
        get
        {
            return this.requireAmountSaleIndexField;
        }
        set
        {
            this.requireAmountSaleIndexField = value;
        }
    }
    
    /// <remarks/>
    public bool EnableCityIndex {
        get {
            return this.enableCityIndexField;
        }
        set {
            this.enableCityIndexField = value;
        }
    }

    /// <remarks/>
    public bool RequireCityIndex
    {
        get
        {
            return this.requireCityIndexField;
        }
        set
        {
            this.requireCityIndexField = value;
        }
    }
    
    /// <remarks/>
    public bool EnableConcurrentIndex {
        get {
            return this.enableConcurrentIndexField;
        }
        set {
            this.enableConcurrentIndexField = value;
        }
    }

    /// <remarks/>
    public bool RequireConcurrentIndex
    {
        get
        {
            return this.requireConcurrentIndexField;
        }
        set
        {
            this.requireConcurrentIndexField = value;
        }
    }
    
    /// <remarks/>
    public bool EnableRequestingParty {
        get {
            return this.enableRequestingPartyField;
        }
        set {
            this.enableRequestingPartyField = value;
        }
    }

    /// <remarks/>
    public bool RequireRequestingParty
    {
        get
        {
            return this.requireRequestingPartyField;
        }
        set
        {
            this.requireRequestingPartyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string _CountyID {
        get {
            return this._CountyIDField;
        }
        set {
            this._CountyIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.secure-recording.com/schemas")]
[System.Xml.Serialization.XmlRootAttribute("Result", Namespace="http://www.secure-recording.com/schemas", IsNullable=false)]
public partial class ResultDetail {
    
    private bool valueField;
    
    /// <remarks/>
    public bool Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
