//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1/WebAPI/")]
        public string SECURE_API_URI_COUNTY {
            get {
                return ((string)(this["SECURE_API_URI_COUNTY"]));
            }
            set {
                this["SECURE_API_URI_COUNTY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Secure123456")]
        public string Default_Submitter_Password {
            get {
                return ((string)(this["Default_Submitter_Password"]));
            }
            set {
                this["Default_Submitter_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Default_Submitter_UserName {
            get {
                return ((string)(this["Default_Submitter_UserName"]));
            }
            set {
                this["Default_Submitter_UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Secure123456")]
        public string Default_County_Password {
            get {
                return ((string)(this["Default_County_Password"]));
            }
            set {
                this["Default_County_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Default_County_UserName {
            get {
                return ((string)(this["Default_County_UserName"]));
            }
            set {
                this["Default_County_UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1/WebAPI/")]
        public string SECURE_API_URI_SUBMITTER {
            get {
                return ((string)(this["SECURE_API_URI_SUBMITTER"]));
            }
            set {
                this["SECURE_API_URI_SUBMITTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Default_County_Password_2Factor {
            get {
                return ((string)(this["Default_County_Password_2Factor"]));
            }
            set {
                this["Default_County_Password_2Factor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwoFactor_Enabled_County {
            get {
                return ((bool)(this["TwoFactor_Enabled_County"]));
            }
            set {
                this["TwoFactor_Enabled_County"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwoFactor_Enabled_Submitter {
            get {
                return ((bool)(this["TwoFactor_Enabled_Submitter"]));
            }
            set {
                this["TwoFactor_Enabled_Submitter"] = value;
            }
        }
    }
}
